"""rename query column to search_term in search_records

Revision ID: a8c429ac6e10
Revises: b21934d1faa6
Create Date: 2025-04-15 10:51:28.513301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8c429ac6e10'
down_revision = 'b21934d1faa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_records', schema=None) as batch_op:
        batch_op.alter_column('query', 
                            new_column_name='search_term',
                            existing_type=sa.String(),
                            nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_records', schema=None) as batch_op:
        batch_op.alter_column('search_term', 
                            new_column_name='query',
                            existing_type=sa.String(),
                            nullable=False)

    # ### end Alembic commands ###